priceMultiplier: 2
issueCreatorMultiplier: 2
incentives:
  comment:
    elements:
      code: 1
      img: 0
      h1: 2
      h2: 2
      h3: 2
      h4: 2
      h5: 2
      h6: 2
      li: 1
      a: 2
      blockquote: 0
      i: 0
    totals:
      word: 0.2
timeLabels:
  - name: "Time: <2 Weeks"
